### ISSUE TITLE
website Prototype \o/

### ISSUE THREAD

**Issue by pierreozoux** [pierreozoux/ihavesomethingtohi.de#4]
Here are the prototype, please feel free to comment on each!
http://www.frenchtouchweb.com/IHSTH/page1.html
http://www.frenchtouchweb.com/IHSTH/page2.html
http://www.frenchtouchweb.com/IHSTH/page3.html

**Comment by pierreozoux** [comment]
## Page 1
- working well on mobile
- CTA should be more CTA
- CTA should be on first sceen (without scrolling, I have a 1280x800 screen, and it is outside)
- I like the "logo"
- is the image CC0?
- we should find a shorter sentence :)
- I like the way additional content is presented
- put a link to frenchtouchweb at the bottom like - design frenchtouchweb
- put a contributor at the bottom - made with love by: ...

## Page 2
- missing the question on top
- put the "how can I protect myself" also on bottom of page 1

## Page 3
- this is great! \o/

I think we should start on implementing that, and puttin this online as soon as possible. even without these comments.
Then we can start to iterate on it!

Let's do it the lean way :)

**Comment by willdurand** [comment]
:+1:

**Comment by dsalber** [comment]
I like the overall look, it feels airy, serious (in the sense of: reliable, knowledgeable), and trustable.

What is missing imho: we don’t explain to people why they should stay instead of clicking on to the next distraction. What will they learn? What will they be able to do that is worth their time and attention. A concise sentence may be enough, maybe instead of the first Yes/No, say: “Yes, I want to learn who is watching me and what I can do about it./No, I don’t care."

Minor nit: Which links are clickable is not obvious. We seem to be using blue for clickable items but it’s somewhat inconsistent.

Hope this helps,
Daniel

**Comment by pierreozoux** [comment]
Ok, you can find the source code on the source branch.
I opened an issue for everything that is missing, please fill it with everything you have in mind!
(I close this issue now)

@dsalber let's meet tonight for a working beer at RuaDaAdica!

**Comment by pierreozoux** [comment]
The site is live :) https://ihavesomethingtohi.de/ cc @pbouda @dsalber @willdurand 

This is the soft launch

Let's get slowly to 0.1 :) https://github.com/pierreozoux/ihavesomethingtohi.de/milestones

**Comment by dsalber** [comment]
Looks good!
